change 書籍の記述どおりに進めるとP236 $helm install metacontroller metacontroller の箇所で以下のエラーが発生します。
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "compositecontrollers.metacontroller.k8s.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "decoratorcontrollers.metacontroller.k8s.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "controllerrevisions.metacontroller.k8s.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first]
```

version: 1.24.7-gke.900で発生した事象です。

エラーは、CustomResourceDefinition API (apiextensions.k8s.io/v1beta1)が version 1.22で削除されたことが関係します。
ref1: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

ref2: The `apiextensions.k8s.io/v1beta1` version of `CustomResourceDefinition` is deprecated and will no longer be served in v1.19.
      https://github.com/kubernetes/kubernetes/pull/79604

書籍中に以下の記述がありますが、github.com/GoogleCloudPlatform/metacontrollerは2022/11/09にpublic archiveされており更新が見込めないため、
「To Be」に記載のようにURLを変更する必要がありました。

As Is
```
$ export MC_URL=https://raw.githubusercontent.com\
/GoogleCloudPlatform/metacontroller/master/manifests/
```

To Be
```
$ export MC_URL=https://raw.githubusercontent.com\
/metacontroller/metacontroller/master/manifests/production
```

また、以下のIssueによると
https://github.com/metacontroller/metacontroller/issues/188

CustomResourceDefinitionに関する記述が別ファイルに移動したためmetacontroller-crds-v1v.yamlを追加で取得する必要がありました。

```
curl -L $MC_URL/metacontroller-crds-v1.yaml > \
metacontroller/templates/metacontroller-crds-v1.yaml
```